#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("PlanetXamarin.Droid.Resource", IsApplication=true)]

namespace PlanetXamarin.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040001
			public const int accent = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int background = 2130968576;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int background_card = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int default_person = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_launcher = 2130837506;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070001
			public const int button_read_full = 2131165185;
			
			// aapt resource value: 0x7f070003
			public const int image = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int linearLayout1 = 2131165188;
			
			// aapt resource value: 0x7f070002
			public const int progressBar = 2131165186;
			
			// aapt resource value: 0x7f070006
			public const int text_author = 2131165190;
			
			// aapt resource value: 0x7f070007
			public const int text_caption = 2131165191;
			
			// aapt resource value: 0x7f070005
			public const int text_title = 2131165189;
			
			// aapt resource value: 0x7f070000
			public const int webview = 2131165184;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Detail = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Master = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int RSSItem = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050000
			public const int app_name = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int read_full = 2131034113;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int BaseTheme = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int Theme = 2131099649;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
